name: Build
on:
  push:
    paths:
      - 'code/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu
          cache: sbt
      - name: Set up sbt
        uses: sbt/setup-sbt@v1
      - name: Run build with sbt
        run: cd code/ && sbt test